

networks:
  autocare-network:
    driver: bridge

services:
  autpart-be:
    build: .
    container_name: autopart-be
    image: faizanraodev/autopart-be:latest
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - DATABASE_URL=postgres:///autoparts
      - POSTGRES_PASSWORD=
      - DEFAULT_ROLE=USER
      - JWT_SECRET=
      - JWT_REFRESH_SECRET=
      - RABBIT_MQ=rabbitmq:5672
      - STRIPE_SECRET_KEY=
      - POSTGRES_HOST=postgres
      - STRIPE_SUCCESS_URL=http://localhost:4000/success?session_id={CHECKOUT_SESSION_ID}
      - STRIPE_RETURN_URL=http://localhost:3000/

      - SENDGRID_API_KEY=
      - EMAIL_SERVICE_FROM=

      - BASE_PATH_FOR_VCDB=autocare.org/AutoCare_VCdb_NA_LDPS_enUS_JSON_20250828
      - BASE_PATH_FOR_PCDB=autocare.org/AutoCare_PCdb_enUS_JSON_20250828
      - BASE_PATH_FOR_BRAND=autocare.org/
      - CC_EMAIL=

    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - autocare-network
   
    working_dir: /usr/src/app
  postgres:
    image: postgres
    container_name: postgres_db
    
    ports:
      - "5430:5432"
    environment:
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    working_dir: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - autocare-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    restart: unless-stopped
    networks:
      - autocare-network
volumes:
  my-postgres-data:
