-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "discount" DOUBLE PRECISION,
ADD COLUMN     "quantity" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "rating" DOUBLE PRECISION,
ALTER COLUMN "price" SET DEFAULT 0;
